name: Dispatch services
on:
  push:
    branches:
      - master
    paths:
      - dispatch.yaml
      - '.github/workflows/dispatch-services.yml'

jobs:
  job:
    name: Deploy public info requests
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/426631733351/locations/global/workloadIdentityPools/github-lgrosz-bhb-static/providers/github'
          service_account: 'bhb-static-github-deploy@bhbh-5f0a6.iam.gserviceaccount.com'
      - uses: google-github-actions/deploy-appengine@v2
        with:
          deliverables: dispatch.yaml
