name: Generate documents
on: [push]
jobs:
  Generate-HTML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://pandoc/core:3.1
        with:
          args: >-
            --standalone
            --metadata title="Public Information Requests"
            --output=info-requests.html
            info-requests.md
      - uses: actions/upload-artifact@v3
        with:
          name: info-requests-html
          path: info-requests.html
